/**
 * Deny/allow matrix for firestore.rules.
 *
 * These run against the Firestore emulator, so they exercise the real rules
 * engine rather than a reading of the rules file. Start them with:
 *
 *   npm install
 *   npm test
 *
 * The emulator needs a JDK on PATH.
 */
const assert = require('node:assert/strict');
const { test, before, after, beforeEach, describe } = require('node:test');
const fs = require('node:fs');
const path = require('node:path');
const {
  initializeTestEnvironment,
  assertFails,
  assertSucceeds,
} = require('@firebase/rules-unit-testing');
const { doc, getDoc, setDoc } = require('firebase/firestore');

const PROJECT_ID = 'lumina-blocks-f5cf1';
const ME = 'uid-me';
const OTHER = 'uid-other';

let testEnv;

before(async () => {
  testEnv = await initializeTestEnvironment({
    projectId: PROJECT_ID,
    firestore: {
      rules: fs.readFileSync(
        path.resolve(__dirname, '../../firestore.rules'),
        'utf8',
      ),
    },
  });
});

after(async () => {
  if (testEnv) await testEnv.cleanup();
});

beforeEach(async () => {
  await testEnv.clearFirestore();
});

/** Seeds a document while bypassing the rules, the way the server would. */
async function seedAsServer(collectionPath, id, data) {
  await testEnv.withSecurityRulesDisabled(async (ctx) => {
    await setDoc(doc(ctx.firestore(), collectionPath, id), data);
  });
}

describe('entitlements', () => {
  test('the owner can read their own entitlements', async () => {
    await seedAsServer('entitlements', ME, { ownedSkus: ['skin_aurora'] });
    const db = testEnv.authenticatedContext(ME).firestore();
    await assertSucceeds(getDoc(doc(db, 'entitlements', ME)));
  });

  test('another signed-in user cannot read them', async () => {
    await seedAsServer('entitlements', ME, { ownedSkus: ['skin_aurora'] });
    const db = testEnv.authenticatedContext(OTHER).firestore();
    await assertFails(getDoc(doc(db, 'entitlements', ME)));
  });

  test('nobody signed out can read them', async () => {
    await seedAsServer('entitlements', ME, { ownedSkus: ['skin_aurora'] });
    const db = testEnv.unauthenticatedContext().firestore();
    await assertFails(getDoc(doc(db, 'entitlements', ME)));
  });

  test('the owner cannot grant themselves an entitlement', async () => {
    const db = testEnv.authenticatedContext(ME).firestore();
    await assertFails(
      setDoc(doc(db, 'entitlements', ME), { ownedSkus: ['skin_aurora'] }),
    );
  });
});

describe('purchase tokens', () => {
  test('a client cannot read a token binding', async () => {
    await seedAsServer('purchaseTokens', 'token-1', { uid: ME });
    const db = testEnv.authenticatedContext(ME).firestore();
    await assertFails(getDoc(doc(db, 'purchaseTokens', 'token-1')));
  });

  test('a client cannot rebind a token to itself', async () => {
    await seedAsServer('purchaseTokens', 'token-1', { uid: OTHER });
    const db = testEnv.authenticatedContext(ME).firestore();
    await assertFails(setDoc(doc(db, 'purchaseTokens', 'token-1'), { uid: ME }));
  });
});

describe('player progress', () => {
  // Loaded from a fixture generated by the Dart model, not hand-written here.
  // The previous version of this suite invented a flat camelCase document that
  // no part of the app produces. All of it passed while every real cloud save
  // was denied, because it was checking a shape that did not exist. Regenerate
  // with: flutter test test/fixtures/cloud_progress_fixture_test.dart
  const realDocument = JSON.parse(
    fs.readFileSync(
      path.resolve(
        __dirname,
        '../../apps/mobile/test/fixtures/cloud_progress_document.json',
      ),
      'utf8',
    ),
  );

  /** A deep copy, so a mutation in one test cannot leak into the next. */
  function documentCopy() {
    return JSON.parse(JSON.stringify(realDocument));
  }

  test('the fixture is the envelope the client actually sends', () => {
    assert.deepEqual(
      Object.keys(realDocument).sort(),
      ['lastSyncUtc', 'progress'],
    );
    assert.ok('schema_version' in realDocument.progress);
    assert.ok('economy_state' in realDocument.progress);
  });

  test('the owner can write the real progress document', async () => {
    const db = testEnv.authenticatedContext(ME).firestore();
    await assertSucceeds(setDoc(doc(db, 'users', ME), documentCopy()));
  });

  test('the owner can merge into it the way the client does', async () => {
    const db = testEnv.authenticatedContext(ME).firestore();
    await assertSucceeds(setDoc(doc(db, 'users', ME), documentCopy()));
    const update = documentCopy();
    update.progress.best_score = 4321;
    await assertSucceeds(
      setDoc(doc(db, 'users', ME), update, { merge: true }),
    );
  });

  test('the owner can read their own progress', async () => {
    await seedAsServer('users', ME, realDocument);
    const db = testEnv.authenticatedContext(ME).firestore();
    await assertSucceeds(getDoc(doc(db, 'users', ME)));
  });

  test('a user cannot write into somebody else document', async () => {
    const db = testEnv.authenticatedContext(OTHER).firestore();
    await assertFails(setDoc(doc(db, 'users', ME), documentCopy()));
  });

  test('a user cannot read somebody else progress', async () => {
    await seedAsServer('users', ME, realDocument);
    const db = testEnv.authenticatedContext(OTHER).firestore();
    await assertFails(getDoc(doc(db, 'users', ME)));
  });

  test('a signed-out client can do neither', async () => {
    await seedAsServer('users', ME, realDocument);
    const db = testEnv.unauthenticatedContext().firestore();
    await assertFails(getDoc(doc(db, 'users', ME)));
    await assertFails(setDoc(doc(db, 'users', ME), documentCopy()));
  });

  test('owned products cannot be granted through the progress document', async () => {
    // The whole reason progress and entitlements are separate: without this,
    // a player grants themselves the catalogue in the same call that saves
    // their score.
    const db = testEnv.authenticatedContext(ME).firestore();
    const cheat = documentCopy();
    cheat.progress.economy_state.owned_product_ids = ['skin_aurora'];
    await assertFails(setDoc(doc(db, 'users', ME), cheat));
  });

  test('unlocked skins cannot be granted either', async () => {
    const db = testEnv.authenticatedContext(ME).firestore();
    const cheat = documentCopy();
    cheat.progress.cosmetics_state.unlocked_skin_ids = ['skin_aurora'];
    await assertFails(setDoc(doc(db, 'users', ME), cheat));
  });

  test('an extra top-level field is rejected', async () => {
    const db = testEnv.authenticatedContext(ME).firestore();
    const extra = documentCopy();
    extra.entitlements = { premiumPass: true };
    await assertFails(setDoc(doc(db, 'users', ME), extra));
  });

  test('a negative best score is rejected', async () => {
    const db = testEnv.authenticatedContext(ME).firestore();
    const bad = documentCopy();
    bad.progress.best_score = -1;
    await assertFails(setDoc(doc(db, 'users', ME), bad));
  });

  test('a best score of the wrong type is rejected', async () => {
    const db = testEnv.authenticatedContext(ME).firestore();
    const bad = documentCopy();
    bad.progress.best_score = 'lots';
    await assertFails(setDoc(doc(db, 'users', ME), bad));
  });

  test('progress cannot be deleted by the client', async () => {
    await seedAsServer('users', ME, realDocument);
    const db = testEnv.authenticatedContext(ME).firestore();
    const { deleteDoc } = require('firebase/firestore');
    await assertFails(deleteDoc(doc(db, 'users', ME)));
  });
});

describe('everything else is closed', () => {
  test('an unlisted collection is not readable or writable', async () => {
    const db = testEnv.authenticatedContext(ME).firestore();
    await assertFails(getDoc(doc(db, 'leaderboards', 'weekly')));
    await assertFails(setDoc(doc(db, 'leaderboards', 'weekly'), { score: 1 }));
  });
});

test('the rules file the tests loaded is the one in the repository', () => {
  const rules = fs.readFileSync(
    path.resolve(__dirname, '../../firestore.rules'),
    'utf8',
  );
  assert.match(rules, /rules_version = '2'/);
  assert.match(rules, /match \/entitlements\/\{uid\}/);
  assert.match(rules, /match \/users\/\{uid\}/);
});
